### ISSUE TITLE
[Drivers] problem with Kinect for xbox 360

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/base#1012]
I can't get RGB image from kinect unsing **openni1Server**, only works well but image is in black
![imagen](https://user-images.githubusercontent.com/16046048/34351615-27f06220-ea1e-11e7-840c-797792eb3037.png)

unsing **openniServer**, I get a error directly
![imagen](https://user-images.githubusercontent.com/16046048/34351636-480acc9e-ea1e-11e7-81be-fc05db777dbc.png)

**Comment by chanfr** [comment]
Hi,

you should use openniserver instead of openni1Server, we should set openni1Server as deprecated to remove it asap. 


regards,
Fran.

**Comment by jmplaza** [comment]
The same on my machine: empty image when connecting cameraViewer to openni1Server...
