### ISSUE TITLE
[Drivers] YoutubeServer only works only with python clients.

### ISSUE THREAD

**Issue by fqez** [JdeRobot/base#1066]
Also it has a deadlock here:

https://github.com/JdeRobot/JdeRobot/blob/master/src/drivers/YoutubeServer/JdeRobot/ImageProviderI.py#L42

here a lock is acquiered, and released inside a try-catch block. Nonetheless, if the try fails, the there is no lock release neither in the catch nor the finally block.

**Comment by pushkalkatara** [comment]
Hi @fqez . For the deadlock, we can apply the lock in the execute function before the [line 33]
 in the execute function.(https://github.com/JdeRobot/JdeRobot/blob/9a34beb93e2af60c48968fe55f6508ba84833583/src/drivers/YoutubeServer/JdeRobot/ImageProviderI.py#L33). I think that would solve this issue. Also the c++ implementation, Can I try the same?
