### ISSUE TITLE
cameraserver_py error: Ice.MessageSizeMax

### ISSUE THREAD

**Issue by igarag** [JdeRobot/base#1114]
cameraserver_py returns the next error:

`protocol error: memory limit exceeded:
requested 2764919 bytes, maximum allowed is 1048576 bytes (see Ice.MessageSizeMax)`

This only happens when cameraserver_py serves videos.

**Comment by abhayraw1** [comment]
What is the resolution of the video frames? 
Is the error spontaneous or does it occur as and when you run the script?

**Comment by fqez** [comment]
This error raises whenever a client (cameraview on this case) tries to fetch images from the server. The server run ok, but the client doesn't. I think you are right, it has to do with the default Ice message size. Do you know how to solve it?
