### ISSUE TITLE
CamServerWeb and CamVizWeb don't get images from camera

### ISSUE THREAD

**Issue by pmvera** [JdeRobot/base#1174]
I'm trying to run this practice and i run the instructions. When i run CamServerWeb, a window appears and the configuration it's OK. The LED of my camera turns on.
When i launch CamVizWeb, the second windows appears and the configurations it's also OK.
But when i "Start" CamVizWeb, the image doesn't show.

I attach several images from the terminals.

- CamServerWeb connected:
![camserver](https://user-images.githubusercontent.com/25414677/40302284-eb701892-5cee-11e8-8f90-473d23e948fd.png)

- CamVizWeb connected:
![camviz](https://user-images.githubusercontent.com/25414677/40302326-10679d00-5cef-11e8-9000-98f9e7a662a0.png)

- Starting CamViWeb:
![start](https://user-images.githubusercontent.com/25414677/40302334-16e3e242-5cef-11e8-8d77-3aceced23865.png)

- CamVizWeb image:
![image](https://user-images.githubusercontent.com/25414677/40302418-55036408-5cef-11e8-813e-9637417312c5.png)

This issue is for @rperezgonz

**Comment by rperezgonz** [comment]
Hi,
Can you show me the developer tools? To open this, you can do it going to View menu in the top screen and it's opened a submenu. In this submenu, select Toggle Developer Tools.

It must be something like this:

![image](https://user-images.githubusercontent.com/33232899/40385659-9c1f45f0-5e07-11e8-81ea-6fa2189a2e73.png)

And the configuration must be something like following:

![image](https://user-images.githubusercontent.com/33232899/40385847-36f798d4-5e08-11e8-9f3f-1d639902a22d.png)

**Comment by PabloMorenoVera** [comment]
Hi @rperezgonz ,
I attach the image of the Developer Tool:
![developper camview tool](https://user-images.githubusercontent.com/25414677/40416031-97a363ba-5e7c-11e8-9200-8b180285a5f9.png)

The configuration of the CamServer and CamViz its okey, its the same as your image.

**Comment by PabloMorenoVera** [comment]
Sorry,

I attach the image of the terminals and the console of both programs (Camserver and CamViz):
![developper console](https://user-images.githubusercontent.com/25414677/40482964-b429e3ee-5f56-11e8-85ec-9325a4a117cc.png)

Thanks!

Pablo

**Comment by rperezgonz** [comment]
To try to detect where the problems may be, Can you do some tests?:

1. CamVizWeb + ros usb cam (https://jderobot.org/Tutorials#Ros_usb_cam_.2B_Cameraview-web).

2. CamVizWeb with nodejs and CamserverWeb with nodejs (you don't run **npm start**, run **node run.js** and then open it in a browser.

3. Try to run CamViz with ICE and camserver (https://jderobot.org/Tutorials#Camserver_.2B_CamViz and Change the instructions to run CamViz by CamViz Web).

With this, we will can know where is the problem, if it's in camviz or in camserver. Any questions you have you tell me

Thanks.

**Comment by PabloMorenoVera** [comment]
Hi Roberto,
I comment the results of the test:
1. The test-launch instruction get mi image but cameraViz doesn't take the images.
2. In the second test, cameraserver connects to the rosbridge and set the camera but camViz doesn't connect to rosbridge.
3. In the third test, camserver and CamViz worked fine. CamViz get the images from the camera.

Thanks for all!

**Comment by rperezgonz** [comment]
Ok, this is strange. It seem that The error is in CamViz and not in CamServer (the first test would have worked correctly).

Can you put in a new console "rostopic list" when CamServer and CamViz have already run? The only thing that I think may be failing is that the topic is not being sent. (This was my problem in the first version)

Thanks

**Comment by PabloMorenoVera** [comment]
Hi Roberto!

When a run CamServer and CamViz and "Start" CamViz, the result of he "rostopic list" is the following:
![rostopic](https://user-images.githubusercontent.com/25414677/40673588-79272f70-6372-11e8-806c-84ac3ea83fe4.png)

Thanks!

**Comment by rperezgonz** [comment]
Ok, we're going to try to do the last test. For this test, it's needed to install web_video_server.

1. sudo apt-get install ros-kinetic-web-video-server
2. roslaunch rosbridge_server rosbridge_websocket.launch
3. rosrun web_video_server web_video_server
4. Run CamServer (if the first doesn't run, try with the ros usb_cam) 
5. http://localhost:8080/stream?topic=/usb_cam/image_raw&type=ros_compressed

if it does not work with CamServer or with usb_cam, the problem is not related to CamServer or CamViz. Probably it will be of some problem in the ros installation. If this works well, it will check that it is failing

**Comment by PabloMorenoVera** [comment]
Hi Rober,
I just run the last test and it works well, i show you an image:
![captura de pantalla 2018-06-04 16 25 01](https://user-images.githubusercontent.com/25414677/40923015-fe91a7bc-6813-11e8-9fc7-637b63ce2796.png)

Thanks!

Pablo,
