### ISSUE TITLE
Refactor all the source code comments to English

### ISSUE THREAD

**Issue by hustcalm** [JdeRobot/base#12]
I also saw there is a discussion in the mailing list about language. As I'm reading the source code of JdeRobot, I find there are some comments maybe in Spanish which can be confused to other developers.

There are a few lines of comments in the root `CMakeLists.txt` and I don't for sure if there are any in other source code files either.

Though this is not a big issue, using English might make other developers feel easier to get onboard:-)

**Comment by rocapal** [comment]
You are right @hustcalm. We are in the process to internationalize the project and we need to be carefuly with this things. We will use this issue to manage this translations

Thanks a lot for your comments!

**Comment by hustcalm** [comment]
@rocapal 
Cool, so glad to hear that you are already on the way!!!
I got another idea, should the mailing list be sent in English?
I'm wondering if I miss something, I receive the mailing list digest in Spanish maybe? Though the topics are discussed in English now. Maybe we should make it universal and all English?

**Comment by abhinavjain241** [comment]
@rocapal 

This would be a nice idea, and it'll be easier for developers from all across the world to make changes to the source code. I would love to contribute here!

**Comment by RoboticsURJC** [comment]
Hi @hustcalm <https://github.com/hustcalm>,

we actually changed the official language for the list messages to English
some days ago. In addition I've just changed the configuration of mailman
server, from now on you should receive the list digests in English too,
both the headers and the contents. Please let us know whether is working
properly for you.

JoseMaria

On Sun, Mar 22, 2015 at 2:45 PM, Lihang Li <notifications@github.com> wrote:

> @rocapal <https://github.com/rocapal>
> Cool, so glad to hear that you are already on the way!!!
> I got another idea, should the mailing list be sent in English?
> I'm wondering if I miss something, I receive the mailing list digest in
> Spanish maybe? Though the topics are discussed in English now. Maybe we
> should make it universal and all English?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoboticsURJC/JdeRobot/issues/12#issuecomment-84610649>
> .
>



-- 
Universidad Rey Juan Carlos
http://gsyc.urjc.es/jmplaza

**Comment by hustcalm** [comment]
Hi @RoboticsURJC ,

Thanks for the update, I make it right for now. In case of others who confused about this, here are my steps for making it right:-)

1. Visit [JdeRobot Mailman](http://gsyc.escet.urjc.es/cgi-bin/mailman/listinfo/jde-developers) and ensure the display language is English
![JdeRobot_Mailman_display_language](https://cloud.githubusercontent.com/assets/1515226/6772611/21ca664a-d13d-11e4-9e4b-b08e1c6218b9.png)

2. Log in by inputing you subscriber Email
![JdeRobot_Mailman_Login](https://cloud.githubusercontent.com/assets/1515226/6772621/5ab85796-d13d-11e4-8a0a-18fd8f30367e.png)

3. Scroll and find the options below
![JdeRobot_Mailman_options_language](https://cloud.githubusercontent.com/assets/1515226/6772623/6136a0d2-d13d-11e4-93be-e1ff0e49c402.png)

<hr />

It' easier for new subscribers, just make sure you select:
![JdeRobot_new_subscriber](https://cloud.githubusercontent.com/assets/1515226/6772632/a748f50c-d13d-11e4-874a-2ade5a672b0f.png)

Cheers,
Lihang

**Comment by gsssrao** [comment]
This would be very helpful for the community and other users. I am interested in contributing here!
