### ISSUE TITLE
PiBot name conflict / project rename proposal

### ISSUE THREAD

**Issue by lr-morales** [JdeRobot/base#1233]
Several projects exists out there under the name of _PiBot_, most of them related to robotics using a Raspberry Pi as one of their main components, ranging from casual robot design and coding to more serious projects.

Maybe we could rename our _PiBot_ to make the project more noteworthy to some less common  and/or unused name, i. e. Pimbot (_Pi modular robot_).

More name ideas and opinions are welcome

**Comment by jmplaza** [comment]
Yes, PiBot seems to be very demanded name (http://www.pibot.org, some [videos](https://vimeo.com/92550891) and even a [paper](https://scholar.google.es/scholar?hl=en&as_sdt=0%2C5&q=Pibot%3AThe+Raspberry+Pi+Controlled+MultiEnvironment+Robot+For+Surveillance+%26+Live+Streaming+&btnG=) ). This name combines Pi regarding the use of RaspberryPI computer, and Bot suffix regarding a robot. Other nice names are also used:
- [PyPiBot](https://github.com/TobiasWeis/pypibot)
- PyBot
- [BerryBot](https://github.com/viru/berrybot)
- RaspBot

That being said, I propose mPiBot, where m may stand for mobile or for modular... It is some kind of redundant, but remains quite close to our original name. PimBot also sounds good to me :-)
