### ISSUE TITLE
JdeRobot installation : missing packages

### ISSUE THREAD

**Issue by Mintu98** [JdeRobot/base#1345]
![1](https://user-images.githubusercontent.com/28685868/54076288-0f5e9b80-42d0-11e9-9d5b-99c7f506ef00.png)
![Screenshot from 2019-03-10 12-00-52](https://user-images.githubusercontent.com/28685868/54076289-0ff73200-42d0-11e9-9d94-92bb3789225f.png)

While installing Jderobot, i could not download packages for NITE2,NITE,libfreenect and PCL_apps.
Please help me with the links to download the missing packages.

**Comment by sleep-404** [comment]
yeah even I'm facing similar problem

**Comment by lr-morales** [comment]
Assuming an Ubuntu system, for libfreenect and pcl, please check first that "universe" repository is enabled and updated. Then search for libfreenect-dev and libpcl-dev packages, which should contain those requirements.

As for NITE and NITE2, can't check for instructions at this moment, sorry.

**Comment by vinay0410** [comment]
Hi @Mintu98 ,
Could you post the end of this CMake output. Nite Dependencies are probably optional and I believe something else is causing this error

**Comment by sleep-404** [comment]
Hi @Mintu98 ,
Can you now build the repository ?

**Comment by Mintu98** [comment]
Thanks @vinay0410 it helped and the problem is resolved. Thanks again! :)
