### ISSUE TITLE
Cmake error 

### ISSUE THREAD

**Issue by EL-SHREIF** [JdeRobot/base#1359]
i have this error when I run command 

>cmake .

version:5.4.0
/home/shiko/base/src/libs/jderobotutil
/home/shiko/base/src/libs/colorspaces
/home/shiko/base/src/libs/colorspacesmm
/home/shiko/base/src/libs/easyiceconfig
/home/shiko/base/src/libs/parallelIce
/home/shiko/base/src/libs/depthLib
/home/shiko/base/src/libs/geometry
/home/shiko/base/src/libs/logger
/home/shiko/base/src/libs/ns
/home/shiko/base/src/libs/progeo
/home/shiko/base/src/libs/pioneer
/home/shiko/base/src/libs/fuzzylib
-- ALUT found at /usr/lib/i386-linux-gnu/libalut.so
-- ardronelib FOUND. Version: autonomy-gps
-- ardronelib libraries: pc_ardrone;pc_ardrone_notool;sdk;vlib;avcodec;avdevice;avfilter;avformat;avutil;swscale
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   chrono
--   date_time
--   atomic
   -- CUDA not found!!
*** Fireware ok
*** GAZEBO LIBRARIES NOT FOUND
-- Found glog    (include: /usr/include, library: /usr/lib/i386-linux-gnu/libglog.so)
*** Goocanvasmm LIBRARIES FOUND
*** ICE ok
 kobuki_LIBRARIES 
kobuki was found in: /opt/ros/kinetic/include
kobuki LIBRARY FOUND IN /opt/ros/kinetic/lib/libkobuki.so;/opt/ros/kinetic/lib/libkobuki_dock_drive.so;/opt/ros/kinetic/lib/libecl_devices.so;/opt/ros/kinetic/lib/libecl_errors.so;/opt/ros/kinetic/lib/libecl_exceptions.so;/opt/ros/kinetic/lib/libecl_formatters.so;/opt/ros/kinetic/lib/libecl_geometry.so;kobuki_LIBRARY8-NOTFOUND;kobuki_LIBRARY9-NOTFOUND;/opt/ros/kinetic/lib/libecl_mobile_robot.so;kobuki_LIBRARY11-NOTFOUND;/opt/ros/kinetic/lib/libecl_streams.so;/opt/ros/kinetic/lib/libecl_threads.so;/opt/ros/kinetic/lib/libecl_time.so;/opt/ros/kinetic/lib/libecl_time_lite.so;/opt/ros/kinetic/lib/libecl_type_traits.so
LIBFREENECT NOT FOUND
*** libusb FOUND
Libxml++ libraries found at 
*** LIBXML2 ok
*** Nite not found
NITE2 library not found
--  NodeJS found
*** OGRe LIBRARIES FOUND: /usr/include/OGRE
-- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") found components:  core flann imgproc ml features2d video objdetect 
-- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") found components:  highgui calib3d 
-- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") found components:  bgsegm 
***OpenCV Version: 3.3.1
***OpenCV CORE LIBS: opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_video;opencv_objdetect
***OpenCV GUI LIBS: opencv_highgui;opencv_calib3d
***OpenCV EXTRA LIBS: opencv_bgsegm
OpenGL libraries found at /usr/lib/i386-linux-gnu/libglut.so;/usr/lib/i386-linux-gnu/libXmu.so;/usr/lib/i386-linux-gnu/libXi.so
CMake Warning at Deps/openni/CMakeLists.txt:12 (MESSAGE):
  Defining 'i386' preprocessor macro due possible XnPlatform.h bug
Call Stack (most recent call first):
  Deps/LoadJderobotDependencies.cmake:12 (include)
  CMakeLists.txt:156 (include)

-- OpenNi found at /usr/lib/libOpenNI.so
-- OpenNI2 found at /usr/include/openni2
-- Using OpenSSL 1.0.2g
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/i386-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- Could NOT find PCL_APPS (missing:  PCL_APPS_LIBRARY) 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
/usr/lib/python3.5:/opt/jderobot/lib/python3.5
/usr/lib/python2.7:/opt/jderobot/lib/python2.7
-- imutils
-- Could NOT find PY_imutils (missing:  PY_IMUTILS) 
-- parse
-- Could NOT find PY_parse (missing:  PY_PARSE) 
-- termcolor
-- Could NOT find PY_termcolor (missing:  PY_TERMCOLOR) 
-- *** QFI_INCLUDE_DIR found
-- *** QFI_LIBRARY found
*** QT LIBRARIES Found Qt5::Widgets;Qt5::Core;Qt5::Gui;Qt5::Svg;Qt5::OpenGL
*** ROS LIBRARIES FOUND : /opt/ros/kinetic/include;/usr/include;/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp
-- Using CATKIN_DEVEL_PREFIX: /home/shiko/base/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/shiko/base/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) (found version "2.7.12")
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
*** LIBTINYXML ok
***VTK FOUND 6.2
*** Xerces ok
/usr/include/libxml2
***YAML-CPP FOUND: /usr/lib/i386-linux-gnu/cmake/yaml-cpp/../../../../include
-- Building ICE Interfaces for:
-- 	CPP
-- 	Java
-- 	Python
-- Processing library config_cpp
-- Processing library visionlib
-- Processing library easyiceconfig
-- Processing library jderobotHandlers
-- Processing library config_py
-- Processing library pioneer
-- Processing library progeo
-- Processing library depthLib
-- Processing library comm_cpp
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:415 (message):
  catkin_package() include dir '/home/shiko/base/src/libs/comm_cpp/include'
  should be placed in the devel space instead of the build space
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  src/libs/comm_cpp/CMakeLists.txt:15 (catkin_package)

-- Processing library geometry
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Processing library xmlParser
-- Processing library fuzzylib
-- Processing library parallelIce_py
-- Processing library resourcelocator
-- Processing library comm_py
-- Processing library ns
-- Processing library easyiceconfig_py
-- Processing library jderobotutil
-- Processing library jderobotViewer
-- Processing library parallelIce
-- Processing library logger
version:5.4.0
-- Processing tool cameraview_py
-- Processing tool colorTuner_py
-- Processing tool cameraview
-- Processing tool navigatorCamera
-- Processing tool namingService
-- Processing tool replayer2
-- Processing tool 3DViewer
-- Processing tool cameraviewjs
-- Processing tool uavviewerjs
-- Processing tool uav_viewer
-- Processing tool cameraCalibrator
-- Processing tool visualStates
-- Processing tool kobukiViewer
-- Processing tool rgbdviewerjs
-- Processing tool rgbdCalibrator
-- Processing tool recorder2
-- Processing tool scratch2jderobot
-- Processing tool visualStates_py
-- Processing tool rgbdManualCalibrator
-- Processing tool uav_viewer_py
-- Processing tool giraffeClient
-- Processing tool rgbdViewer
-- Processing tool kobukiviewerjs
-- Processing tool replayController
-- Processing tool pantilt_teleop_py
-- Processing driver gazeboserver
-- Processing driver openniServer
-- Processing driver laser_server
-- Processing driver evicam_driver
-- Processing driver kobuki_driver
CMake Warning (dev) at src/drivers/kobuki_driver/CMakeLists.txt:16 (link_directories):
  This command specifies the relative path

    kobuki_LIBRARY8-NOTFOUND

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/drivers/kobuki_driver/CMakeLists.txt:16 (link_directories):
  This command specifies the relative path

    kobuki_LIBRARY9-NOTFOUND

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/drivers/kobuki_driver/CMakeLists.txt:16 (link_directories):
  This command specifies the relative path

    kobuki_LIBRARY11-NOTFOUND

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Processing driver kinect2server
Disabled
-- Processing driver cameraserver
-- Processing driver giraffeServer
-- Processing driver emSensorDriver
WiringPi library is required to build emSensorDriver, skipping driver bulid.
-- Processing driver ardrone_server
-- Processing driver pclRGBDServer
-- Processing driver openni1Server
-- Processing driver MAVLinkServer
-- Processing sample basic_component
-- Processing sample opencvdemo
-- Processing sample basic_component_py
-- Processing sample basic_server
fatal: Not a git repository (or any of the parent directories): .git
deps-dev
dpkg-deb: building package 'jderobot-deps-dev' in '.dpkg_pkgs/jderobot-deps-dev_5.6.1_all.deb'.
drivers
dpkg-deb: building package 'jderobot-drivers' in '.dpkg_pkgs/jderobot-drivers_5.6.1_all.deb'.
examples
dpkg-deb: building package 'jderobot-examples' in '.dpkg_pkgs/jderobot-examples_5.6.1_all.deb'.
libs
dpkg-deb: building package 'jderobot-libs' in '.dpkg_pkgs/jderobot-libs_5.6.1_all.deb'.
tools
dpkg-deb: building package 'jderobot-tools' in '.dpkg_pkgs/jderobot-tools_5.6.1_all.deb'.
zeroc-ice-python
dpkg-deb: building package 'jderobot-zeroc-ice-python' in '.dpkg_pkgs/jderobot-zeroc-ice-python_5.6.1_all.deb'.
jderobot
dpkg-deb: building package 'jderobot' in '.dpkg_pkgs/jderobot_5.6.1_all.deb'.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
kobuki_LIBRARY11
    linked by target "kobuki_driver" in directory /home/shiko/base/src/drivers/kobuki_driver
kobuki_LIBRARY8
    linked by target "kobuki_driver" in directory /home/shiko/base/src/drivers/kobuki_driver
kobuki_LIBRARY9
    linked by target "kobuki_driver" in directory /home/shiko/base/src/drivers/kobuki_driver

-- Configuring incomplete, errors occurred!
See also "/home/shiko/base/CMakeFiles/CMakeOutput.log".
See also "/home/shiko/base/CMakeFiles/CMakeError.log".

=======================================================
and I make sure that I install 
Kobuki robot libraries

**Comment by sleep-404** [comment]
Hello @EL-SHREIF  , just made a video on how to download and compile JDE robot in a freshly installed Ubuntu 16.04. Sorry the video is awfully long and is of less clarity, did not get enough time to edit it, as installing itself took substantial amount of time. You can skip many parts as most of the video though. I apologise once again.
There are a few things you need to know before watching the video:
1.) I installed Opencv in the video , which was not required for 16.04(required only for 18.04)
2.) After installing dependencies ,while building, errors popped up regarding **opencv** and **roscpp** , all I did was closed all the terminal and re-opened them. This fixed it . You need not install anything extra
3.) For errors on zero-ice-python , please refer to [this](https://github.com/JdeRobot/base/issues/1345) issue
4.) Error regarding **OpenCV_INCLUDE_DIR** was fixed by removing the build directory and again creating it back.
The video can be found [here](https://www.youtube.com/watch?v=vSjTg_Nfo_8&feature=youtu.be). Hope you find this helpful.

**Comment by Pravin854** [comment]
Try `sudo apt-get install ros-kinetic-kobuki`

**Comment by EL-SHREIF** [comment]
I have this error @sleep-404 
 
>shiko@PC:~/base$ sudo apt-get install jderobot-deps-dev

[sudo] password for shiko: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jderobot-deps-dev : Depends: jderobot-openni2 but it is not installable
                     Depends: jderobot-libfreenect-dev but it is not installable
                     Depends: qfi but it is not installable
                     Depends: ardronelib but it is not installable
                     Depends: libzeroc-ice3.6 but it is not installable
                     Depends: zeroc-ice-utils but it is not installable
                     Depends: libzeroc-icestorm3.6 but it is not installable
                     Depends: jderobot-openni2 but it is not installable
                     Depends: jderobot-libfreenect-dev but it is not installable
                     Depends: qfi but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by EL-SHREIF** [comment]
> I have this error @sleep-404
> 
> > shiko@PC:~/base$ sudo apt-get install jderobot-deps-dev
> 
> [sudo] password for shiko:
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> jderobot-deps-dev : Depends: jderobot-openni2 but it is not installable
> Depends: jderobot-libfreenect-dev but it is not installable
> Depends: qfi but it is not installable
> Depends: ardronelib but it is not installable
> Depends: libzeroc-ice3.6 but it is not installable
> Depends: zeroc-ice-utils but it is not installable
> Depends: libzeroc-icestorm3.6 but it is not installable
> Depends: jderobot-openni2 but it is not installable
> Depends: jderobot-libfreenect-dev but it is not installable
> Depends: qfi but it is not installable
> E: Unable to correct problems, you have held broken packages.

this can be solve by using  sudo aptitude not sudo apt-get

**Comment by EL-SHREIF** [comment]
> i have this error when I run command
> 
> > cmake .
> 
> version:5.4.0
> /home/shiko/base/src/libs/jderobotutil
> /home/shiko/base/src/libs/colorspaces
> /home/shiko/base/src/libs/colorspacesmm
> /home/shiko/base/src/libs/easyiceconfig
> /home/shiko/base/src/libs/parallelIce
> /home/shiko/base/src/libs/depthLib
> /home/shiko/base/src/libs/geometry
> /home/shiko/base/src/libs/logger
> /home/shiko/base/src/libs/ns
> /home/shiko/base/src/libs/progeo
> /home/shiko/base/src/libs/pioneer
> /home/shiko/base/src/libs/fuzzylib
> -- ALUT found at /usr/lib/i386-linux-gnu/libalut.so
> -- ardronelib FOUND. Version: autonomy-gps
> -- ardronelib libraries: pc_ardrone;pc_ardrone_notool;sdk;vlib;avcodec;avdevice;avfilter;avformat;avutil;swscale
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> -- system
> -- filesystem
> -- thread
> -- chrono
> -- date_time
> -- atomic
> -- CUDA not found!!
> *** Fireware ok
> *** GAZEBO LIBRARIES NOT FOUND
> -- Found glog (include: /usr/include, library: /usr/lib/i386-linux-gnu/libglog.so)
> *** Goocanvasmm LIBRARIES FOUND
> *** ICE ok
> kobuki_LIBRARIES
> kobuki was found in: /opt/ros/kinetic/include
> kobuki LIBRARY FOUND IN /opt/ros/kinetic/lib/libkobuki.so;/opt/ros/kinetic/lib/libkobuki_dock_drive.so;/opt/ros/kinetic/lib/libecl_devices.so;/opt/ros/kinetic/lib/libecl_errors.so;/opt/ros/kinetic/lib/libecl_exceptions.so;/opt/ros/kinetic/lib/libecl_formatters.so;/opt/ros/kinetic/lib/libecl_geometry.so;kobuki_LIBRARY8-NOTFOUND;kobuki_LIBRARY9-NOTFOUND;/opt/ros/kinetic/lib/libecl_mobile_robot.so;kobuki_LIBRARY11-NOTFOUND;/opt/ros/kinetic/lib/libecl_streams.so;/opt/ros/kinetic/lib/libecl_threads.so;/opt/ros/kinetic/lib/libecl_time.so;/opt/ros/kinetic/lib/libecl_time_lite.so;/opt/ros/kinetic/lib/libecl_type_traits.so
> LIBFREENECT NOT FOUND
> *** libusb FOUND
> Libxml++ libraries found at
> *** LIBXML2 ok
> *** Nite not found
> NITE2 library not found
> -- NodeJS found
> *** OGRe LIBRARIES FOUND: /usr/include/OGRE
> -- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") found components: core flann imgproc ml features2d video objdetect
> -- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") found components: highgui calib3d
> -- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") found components: bgsegm
> ***OpenCV Version: 3.3.1
> ***OpenCV CORE LIBS: opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_video;opencv_objdetect
> ***OpenCV GUI LIBS: opencv_highgui;opencv_calib3d
> ***OpenCV EXTRA LIBS: opencv_bgsegm
> OpenGL libraries found at /usr/lib/i386-linux-gnu/libglut.so;/usr/lib/i386-linux-gnu/libXmu.so;/usr/lib/i386-linux-gnu/libXi.so
> CMake Warning at Deps/openni/CMakeLists.txt:12 (MESSAGE):
> Defining 'i386' preprocessor macro due possible XnPlatform.h bug
> Call Stack (most recent call first):
> Deps/LoadJderobotDependencies.cmake:12 (include)
> CMakeLists.txt:156 (include)
> 
> -- OpenNi found at /usr/lib/libOpenNI.so
> -- OpenNI2 found at /usr/include/openni2
> -- Using OpenSSL 1.0.2g
> -- The imported target "vtkRenderingPythonTkWidgets" references the file
> "/usr/lib/i386-linux-gnu/libvtkRenderingPythonTkWidgets.so"
> but this file does not exist. Possible reasons include:
> 
>     * The file was deleted, renamed, or moved to another location.
> 
>     * An install or uninstall procedure did not complete successfully.
> 
>     * The installation package was faulty and contained
>       "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
>       but not all the files it references.
> 
> 
> -- The imported target "vtk" references the file
> "/usr/bin/vtk"
> but this file does not exist. Possible reasons include:
> 
>     * The file was deleted, renamed, or moved to another location.
> 
>     * An install or uninstall procedure did not complete successfully.
> 
>     * The installation package was faulty and contained
>       "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
>       but not all the files it references.
> 
> 
> -- Could NOT find PCL_APPS (missing: PCL_APPS_LIBRARY)
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3")
> -- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2")
> /usr/lib/python3.5:/opt/jderobot/lib/python3.5
> /usr/lib/python2.7:/opt/jderobot/lib/python2.7
> -- imutils
> -- Could NOT find PY_imutils (missing: PY_IMUTILS)
> -- parse
> -- Could NOT find PY_parse (missing: PY_PARSE)
> -- termcolor
> -- Could NOT find PY_termcolor (missing: PY_TERMCOLOR)
> -- *** QFI_INCLUDE_DIR found
> -- *** QFI_LIBRARY found
> *** QT LIBRARIES Found Qt5::Widgets;Qt5::Core;Qt5::Gui;Qt5::Svg;Qt5::OpenGL
> *** ROS LIBRARIES FOUND : /opt/ros/kinetic/include;/usr/include;/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp
> -- Using CATKIN_DEVEL_PREFIX: /home/shiko/base/devel
> -- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
> -- This workspace overlays: /opt/ros/kinetic
> -- Found PythonInterp: /usr/bin/python2 (found version "2.7.12")
> -- Using PYTHON_EXECUTABLE: /usr/bin/python2
> -- Using Debian Python package layout
> -- Using empy: /usr/bin/empy
> -- Using CATKIN_ENABLE_TESTING: ON
> -- Skip enable_testing() when building binary package
> -- Using CATKIN_TEST_RESULTS_DIR: /home/shiko/base/test_results
> -- Found gmock sources under '/usr/src/gmock': gmock will be built
> -- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (found version "2.7.12")
> -- Found gtest sources under '/usr/src/gmock': gtests will be built
> -- Using Python nosetests: /usr/bin/nosetests-2.7
> -- catkin 0.7.14
> -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
> *** LIBTINYXML ok
> ***VTK FOUND 6.2
> *** Xerces ok
> /usr/include/libxml2
> ***YAML-CPP FOUND: /usr/lib/i386-linux-gnu/cmake/yaml-cpp/../../../../include
> -- Building ICE Interfaces for:
> -- CPP
> -- Java
> -- Python
> -- Processing library config_cpp
> -- Processing library visionlib
> -- Processing library easyiceconfig
> -- Processing library jderobotHandlers
> -- Processing library config_py
> -- Processing library pioneer
> -- Processing library progeo
> -- Processing library depthLib
> -- Processing library comm_cpp
> CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:415 (message):
> catkin_package() include dir '/home/shiko/base/src/libs/comm_cpp/include'
> should be placed in the devel space instead of the build space
> Call Stack (most recent call first):
> /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
> src/libs/comm_cpp/CMakeLists.txt:15 (catkin_package)
> 
> -- Processing library geometry
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> -- system
> -- filesystem
> -- Processing library xmlParser
> -- Processing library fuzzylib
> -- Processing library parallelIce_py
> -- Processing library resourcelocator
> -- Processing library comm_py
> -- Processing library ns
> -- Processing library easyiceconfig_py
> -- Processing library jderobotutil
> -- Processing library jderobotViewer
> -- Processing library parallelIce
> -- Processing library logger
> version:5.4.0
> -- Processing tool cameraview_py
> -- Processing tool colorTuner_py
> -- Processing tool cameraview
> -- Processing tool navigatorCamera
> -- Processing tool namingService
> -- Processing tool replayer2
> -- Processing tool 3DViewer
> -- Processing tool cameraviewjs
> -- Processing tool uavviewerjs
> -- Processing tool uav_viewer
> -- Processing tool cameraCalibrator
> -- Processing tool visualStates
> -- Processing tool kobukiViewer
> -- Processing tool rgbdviewerjs
> -- Processing tool rgbdCalibrator
> -- Processing tool recorder2
> -- Processing tool scratch2jderobot
> -- Processing tool visualStates_py
> -- Processing tool rgbdManualCalibrator
> -- Processing tool uav_viewer_py
> -- Processing tool giraffeClient
> -- Processing tool rgbdViewer
> -- Processing tool kobukiviewerjs
> -- Processing tool replayController
> -- Processing tool pantilt_teleop_py
> -- Processing driver gazeboserver
> -- Processing driver openniServer
> -- Processing driver laser_server
> -- Processing driver evicam_driver
> -- Processing driver kobuki_driver
> CMake Warning (dev) at src/drivers/kobuki_driver/CMakeLists.txt:16 (link_directories):
> This command specifies the relative path
> 
> ```
> kobuki_LIBRARY8-NOTFOUND
> ```
> 
> as a link directory.
> 
> Policy CMP0015 is not set: link_directories() treats paths relative to the
> source dir. Run "cmake --help-policy CMP0015" for policy details. Use the
> cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at src/drivers/kobuki_driver/CMakeLists.txt:16 (link_directories):
> This command specifies the relative path
> 
> ```
> kobuki_LIBRARY9-NOTFOUND
> ```
> 
> as a link directory.
> 
> Policy CMP0015 is not set: link_directories() treats paths relative to the
> source dir. Run "cmake --help-policy CMP0015" for policy details. Use the
> cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at src/drivers/kobuki_driver/CMakeLists.txt:16 (link_directories):
> This command specifies the relative path
> 
> ```
> kobuki_LIBRARY11-NOTFOUND
> ```
> 
> as a link directory.
> 
> Policy CMP0015 is not set: link_directories() treats paths relative to the
> source dir. Run "cmake --help-policy CMP0015" for policy details. Use the
> cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Processing driver kinect2server
> Disabled
> -- Processing driver cameraserver
> -- Processing driver giraffeServer
> -- Processing driver emSensorDriver
> WiringPi library is required to build emSensorDriver, skipping driver bulid.
> -- Processing driver ardrone_server
> -- Processing driver pclRGBDServer
> -- Processing driver openni1Server
> -- Processing driver MAVLinkServer
> -- Processing sample basic_component
> -- Processing sample opencvdemo
> -- Processing sample basic_component_py
> -- Processing sample basic_server
> fatal: Not a git repository (or any of the parent directories): .git
> deps-dev
> dpkg-deb: building package 'jderobot-deps-dev' in '.dpkg_pkgs/jderobot-deps-dev_5.6.1_all.deb'.
> drivers
> dpkg-deb: building package 'jderobot-drivers' in '.dpkg_pkgs/jderobot-drivers_5.6.1_all.deb'.
> examples
> dpkg-deb: building package 'jderobot-examples' in '.dpkg_pkgs/jderobot-examples_5.6.1_all.deb'.
> libs
> dpkg-deb: building package 'jderobot-libs' in '.dpkg_pkgs/jderobot-libs_5.6.1_all.deb'.
> tools
> dpkg-deb: building package 'jderobot-tools' in '.dpkg_pkgs/jderobot-tools_5.6.1_all.deb'.
> zeroc-ice-python
> dpkg-deb: building package 'jderobot-zeroc-ice-python' in '.dpkg_pkgs/jderobot-zeroc-ice-python_5.6.1_all.deb'.
> jderobot
> dpkg-deb: building package 'jderobot' in '.dpkg_pkgs/jderobot_5.6.1_all.deb'.
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> kobuki_LIBRARY11
> linked by target "kobuki_driver" in directory /home/shiko/base/src/drivers/kobuki_driver
> kobuki_LIBRARY8
> linked by target "kobuki_driver" in directory /home/shiko/base/src/drivers/kobuki_driver
> kobuki_LIBRARY9
> linked by target "kobuki_driver" in directory /home/shiko/base/src/drivers/kobuki_driver
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/shiko/base/CMakeFiles/CMakeOutput.log".
> See also "/home/shiko/base/CMakeFiles/CMakeError.log".
> 
> =======================================================
> and I make sure that I install
> Kobuki robot libraries

this can be solve by updating the repo by the existing one
