### ISSUE TITLE
Error While launching camserver

### ISSUE THREAD

**Issue by ShyamGanatra** [JdeRobot/base#1367]
While trying to launch the camserver I'm getting an 

> Error:
 communicator not destroyed during global destruction. 
below is attached Screenshot of error.

![error](https://user-images.githubusercontent.com/21352161/55666801-54df9b80-5871-11e9-9af1-d0ee2624019b.jpg)

**Comment by fqez** [comment]
Hi @ShyamGanatra, two quick questions:

* Is that Ubuntu 16.04 or Ubuntu 18.04?
* Have you compiled the project or have you installed it from debian packages?

**Comment by wasifferoze** [comment]
Hi @fqez 
I'm facing the same problem while using docker image. Please can you point to some helpful resource
