### ISSUE TITLE
[Installation] Ubuntu 18.04

### ISSUE THREAD

**Issue by MostafaAhmed95** [JdeRobot/base#1384]
This step

  Add JdeRobot repository (using dedicated file /etc/apt/sources.list.d/jderobot.list) For Ubuntu Xenial(16.04):
sudo sh -c 'cat<<EOF>/etc/apt/sources.list.d/jderobot.list
# for ubuntu 16.04 LTS (64 bit)
deb [arch=amd64] http://wiki.jderobot.org/apt bionic main
EOF'

is also essential to setup in 18.04

**Comment by jmplaza** [comment]
Hi @MostafaAhmed95 , feel free to update that README file with your own pull-request on this issue. You have successfully installed JdeRobot/base so, replace any obsolete line on that README by the successful new ones.

**Comment by jmplaza** [comment]
solved in #1385  Thanks @MostafaAhmed95 !
