### ISSUE TITLE
E: Unable to locate package jderobot

### ISSUE THREAD

**Issue by ayushmankumar7** [JdeRobot/base#1388]
I faced many problems while setting up the application on my local machine.

![Screenshot from 2020-02-23 16-09-26](https://user-images.githubusercontent.com/41910134/75110673-f6710680-5656-11ea-997e-f9100257bc82.png)

**Comment by jmplaza** [comment]
Hi @ayushmankumar7 , take a look at the [installation instructions for JdeRobot-base](https://jderobot.github.io/RoboticsAcademy/installation/#jderobot-base) in JdeRobot Academy. They are the most updated ones.

The README file at JdeRobot-base should be updated with that content too...

**Comment by ayushmankumar7** [comment]
Release file for "eoan" not present. 

![Screenshot from 2020-02-23 18-00-21](https://user-images.githubusercontent.com/41910134/75112079-69ce4480-5666-11ea-92cd-97e26a0f7dbd.png)

Following Error is popping up. 
![Screenshot from 2020-02-23 18-02-44](https://user-images.githubusercontent.com/41910134/75112122-c3367380-5666-11ea-881e-11168373c2f8.png)


I tried doing installing it using the Bionic dist on my eoan dist. It says "you have held broken packages"

**Comment by jmplaza** [comment]
Hi @ayushmankumar7, Ubuntu 19.04 (Eoan Ermine) is NOT supported, Jderobot-base debian package will NOT be created for it. We only support LTS Ubuntu distributions.

Alternatively you may work (a) directly from JdeRobot-base source code or (b) use a virtual machine or docker container with Ubuntu 18.04 and install there the jderobot-base debian package.

**Comment by ayushmankumar7** [comment]
It's alright sir. Thanks you the information.
