### ISSUE TITLE
Error while doing Manual Installation

### ISSUE THREAD

**Issue by rk080299** [JdeRobot/base#1392]
While adding each dependency manually and build the packages following error while performing cmake  .. in the build directory  and the output of CMakeError.log

Output of cmake

version:7.4.0
/home/leo/JdeRobot/base/src/libs/jderobotutil
/home/leo/JdeRobot/base/src/libs/colorspaces
/home/leo/JdeRobot/base/src/libs/colorspacesmm
/home/leo/JdeRobot/base/src/libs/easyiceconfig
/home/leo/JdeRobot/base/src/libs/parallelIce
/home/leo/JdeRobot/base/src/libs/depthLib
/home/leo/JdeRobot/base/src/libs/geometry
/home/leo/JdeRobot/base/src/libs/logger
/home/leo/JdeRobot/base/src/libs/ns
/home/leo/JdeRobot/base/src/libs/progeo
/home/leo/JdeRobot/base/src/libs/pioneer
/home/leo/JdeRobot/base/src/libs/fuzzylib
*** ALUT not found
-- ardronelib FOUND. Version: autonomy-gps
-- ardronelib libraries: pc_ardrone;pc_ardrone_notool;sdk;vlib;avcodec;avdevice;avfilter;avformat;avutil;swscale
-- Found Boost: /usr/include (found version "1.65.1") found components: system filesystem thread chrono date_time atomic 
   -- CUDA not found!!
*** Fireware ok
*** GAZEBO LIBRARIES FOUND: /usr/include/gazebo-9;/usr/include/sdformat-6.0;/usr/include/ignition/transport4;/usr/include/ignition/msgs1;/usr/include/ignition/fuel_tools1;/usr/include/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu/libzip/include;/usr/include/ignition/common1;/usr/include/ignition/math4;/usr/include/uuid;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/x86_64-linux-gnu - /usr/include/OGRE
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
*** Goocanvasmm LIBRARIES FOUND
*** ICE ok
CMake Warning at Deps/ice/CMakeLists.txt:38 (MESSAGE):
  *** IceUtil not found
Call Stack (most recent call first):
  Deps/LoadJderobotDependencies.cmake:12 (include)
  CMakeLists.txt:165 (include)

LIBFREENECT NOT FOUND
*** libusb FOUND
Libxml++ libraries found at 
*** LIBXML2 ok
CMake Warning at Deps/mmal/CMakeLists.txt:9 (FIND_PACKAGE):
  By not providing "FindMMAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MMAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "MMAL" with any of
  the following names:

    MMALConfig.cmake
    mmal-config.cmake

  Add the installation prefix of "MMAL" to CMAKE_PREFIX_PATH or set
  "MMAL_DIR" to a directory containing one of the above files.  If "MMAL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  Deps/LoadJderobotDependencies.cmake:12 (include)
  CMakeLists.txt:165 (include)

*** Nite not found
NITE2 library not found
--  NodeJS found
*** OGRe LIBRARIES FOUND: /usr/include/OGRE
-- Found OpenCV: /home/leo/intel/openvino_2020.1.023/opencv (found version "4.2.0") found components: core flann imgproc ml features2d video objdetect 
-- Found OpenCV: /home/leo/intel/openvino_2020.1.023/opencv (found version "4.2.0") found components: highgui calib3d 
-- Could NOT find OpenCV (missing: contrib gpu legacy) (found version "4.2.0")
CMake Warning at Deps/opencv/CMakeLists.txt:37 (FIND_PACKAGE):
  Found package configuration file:

    /home/leo/intel/openvino_2020.1.023/opencv/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.
Call Stack (most recent call first):
  Deps/LoadJderobotDependencies.cmake:12 (include)
  CMakeLists.txt:165 (include)

***OpenCV Version: 4.2.0
***OpenCV CORE LIBS: opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_video;opencv_objdetect
***OpenCV GUI LIBS: opencv_highgui;opencv_calib3d
***OpenCV EXTRA LIBS: 
CMake Warning (dev) at /usr/local/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  Deps/opengl/CMakeLists.txt:3 (find_package)
  Deps/LoadJderobotDependencies.cmake:12 (include)
  CMakeLists.txt:165 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

OpenGL libraries found at /usr/lib/x86_64-linux-gnu/libglut.so;/usr/lib/x86_64-linux-gnu/libXmu.so;/usr/lib/x86_64-linux-gnu/libXi.so
-- OpenNi found at /usr/lib/libOpenNI.so
-- OpenNI2 found at /usr/include/openni2
-- Using OpenSSL 1.1.1
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
/usr/lib/python3.6:/opt/jderobot/lib/python3.6
/usr/lib/python2.7:/opt/jderobot/lib/python2.7
-- kurt
-- Could NOT find PY_kurt (missing: PY_KURT) 
-- parse
-- Could NOT find PY_parse (missing: PY_PARSE) 
-- termcolor
-- Could NOT find PY_termcolor (missing: PY_TERMCOLOR) 
-- *** QFI_INCLUDE_DIR found
-- *** QFI_LIBRARY found
*** QT LIBRARIES Found Qt5::Widgets;Qt5::Core;Qt5::Gui;Qt5::Svg;Qt5::OpenGL
*** ROS LIBRARIES FOUND : /opt/ros/melodic/include;/usr/include;/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp
-- Using CATKIN_DEVEL_PREFIX: /home/leo/JdeRobot/base/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/leo/JdeRobot/base/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (found version "2.7.17")
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.20
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
*** LIBTINYXML ok
***VTK FOUND 6.3
*** Xerces ok
/usr/include/libxml2
***YAML-CPP FOUND: /usr/lib/x86_64-linux-gnu/cmake/yaml-cpp/../../../../include
youtube-dl found at /usr/bin/youtube-dl
-- Building ICE Interfaces for:
-- 	CPP
-- 	Python
CMake Warning (dev) at src/types/cpp/CMakeLists.txt:25 (set):
  implicitly converting 'STRINGS' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Processing library config_cpp
CMake Warning (dev) at src/libs/config_cpp/CMakeLists.txt:37 (set):
  implicitly converting 'STRINGS' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Processing library comm_cpp
CMake Warning (dev) at src/libs/comm_cpp/CMakeLists.txt:150 (set):
  implicitly converting 'STRINGS' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Processing library comm_py
-- Processing library config_py
-- Processing library depthLib
-- Processing library easyiceconfig
CMake Warning (dev) at src/libs/easyiceconfig/CMakeLists.txt:49 (set):
  implicitly converting 'STRINGS' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Processing library easyiceconfig_py
-- Processing library fuzzylib
-- Processing library geometry
-- Found Boost: /usr/include (found version "1.65.1") found components: system filesystem 
-- Processing library jderobotHandlers
-- Processing library jderobotViewer
-- Processing library jderobotutil
-- Processing library logger
version:7.4.0
-- Processing library ns
-- Processing library parallelIce
-- Processing library parallelIce_py
-- Processing library progeo
-- Processing library resourcelocator
CMake Warning (dev) at src/libs/resourcelocator/CMakeLists.txt:40 (set):
  implicitly converting 'STRINGS' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Processing library visionlib
-- Processing library xmlParser
-- Processing tool colorTuner_py
-- Processing tool namingService
-- Processing tool navigatorCamera
-- Processing tool pantilt_teleop_py
-- Processing tool recorder2
-- Processing tool replayController
-- Processing tool replayer2
-- Processing driver MAVLinkServer
-- Processing driver YoutubeServer
-- Processing driver camserver
-- Processing driver camserver_py
-- Processing driver emSensorDriver
WiringPi library is required to build emSensorDriver, skipping driver bulid.
-- Processing driver evicam_driver
-- Processing driver gazebo
-- Processing plugin ball
-- Processing plugin car
-- Processing plugin dummycar
-- Processing plugin f1
-- Processing plugin flyingKinect
-- Processing plugin formula1
-- Processing plugin gazebo_ros_screw_plugin
CMake Warning (dev) at /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:1287 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:1921 (_Boost_MISSING_DEPENDENCIES)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:159 (find_package)
  src/drivers/gazebo/plugins/gazebo_ros_screw_plugin/CMakeLists.txt:9 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.40.0") found components: thread signals system filesystem program_options regex iostreams date_time chrono atomic 
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread (found version "3.0.0") 
-- Found Boost: /usr/include (found version "1.65.1")  
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread (found suitable version "3.0.0", minimum required is "2.3.0") 
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.2.5
-- Checking for module 'uuid'
--   Found uuid, version 2.31.1
-- Found UUID: TRUE  
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.0.0
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
-- Found UUID: TRUE  
-- Checking for module 'gts'
--   Found gts, version 0.7.6
-- Checking for module 'libswscale'
--   Found libswscale, version 4.8.100
-- Checking for module 'libavdevice >= 56.4.100'
--   Found libavdevice , version 57.10.100
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.1.7
-- Checking for module 'libzip'
--   Found libzip, version 1.1.2
-- Processing plugin gymkhana
-- Processing plugin holo_car
-- Processing plugin kinect
-- Processing plugin mbot
-- Processing plugin opel
-- Processing plugin pibot
CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:13 (add_library):
  add_library cannot create target "motorsMBOT" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory
  "/home/leo/JdeRobot/base/src/drivers/gazebo/plugins/mbot".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:14 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libIce.so" to target
  "motorsMBOT" which is not built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:22 (add_library):
  add_library cannot create target "sonarMBOT" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory
  "/home/leo/JdeRobot/base/src/drivers/gazebo/plugins/mbot".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:23 (target_link_libraries):
  Attempt to add link library "SonarPlugin" to target "sonarMBOT" which is
  not built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:32 (add_library):
  add_library cannot create target "pose3dMBOT" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory
  "/home/leo/JdeRobot/base/src/drivers/gazebo/plugins/mbot".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:33 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libIce.so" to target
  "pose3dMBOT" which is not built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:41 (add_library):
  add_library cannot create target "camera_dumpMBOT" because another target
  with the same name already exists.  The existing target is a shared library
  created in source directory
  "/home/leo/JdeRobot/base/src/drivers/gazebo/plugins/mbot".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:42 (target_link_libraries):
  Attempt to add link library "CameraPlugin" to target "camera_dumpMBOT"
  which is not built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:51 (add_library):
  add_library cannot create target "irMBOT" because another target with the
  same name already exists.  The existing target is a shared library created
  in source directory
  "/home/leo/JdeRobot/base/src/drivers/gazebo/plugins/mbot".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/drivers/gazebo/plugins/pibot/CMakeLists.txt:52 (target_link_libraries):
  Attempt to add link library "CameraPlugin" to target "irMBOT" which is not
  built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.

-- Processing plugin pioneer
-- Processing plugin quadrotor
-- Processing plugin roomba
-- Processing plugin solo
-- Processing plugin taxiholoLaser
-- Processing plugin turtlebot
-- Processing driver giraffeServer
-- Processing driver kinect2server
Disabled
-- Processing driver openni1Server
-- Processing driver openniServer
-- Processing driver pclRGBDServer
-- Processing sample basic_component
-- Processing sample basic_component_py
-- Processing sample basic_server
-- Processing sample opencvdemo
-- Processing sample visualStates
deps-dev
dpkg-deb: building package 'jderobot-deps-dev' in '.dpkg_pkgs/jderobot-deps-dev_6.0.0_all.deb'.
drivers
dpkg-deb: building package 'jderobot-drivers' in '.dpkg_pkgs/jderobot-drivers_6.0.0_all.deb'.
examples
dpkg-deb: building package 'jderobot-examples' in '.dpkg_pkgs/jderobot-examples_6.0.0_all.deb'.
libs
dpkg-deb: building package 'jderobot-libs' in '.dpkg_pkgs/jderobot-libs_6.0.0_all.deb'.
tools
dpkg-deb: building package 'jderobot-tools' in '.dpkg_pkgs/jderobot-tools_6.0.0_all.deb'.
zeroc-ice-python
cp: cannot create regular file '.dpkg_pkgs/jderobot-zeroc-ice-python_6.0.0_all/DEBIAN/postinst': Permission denied
cp: cannot create regular file '.dpkg_pkgs/jderobot-zeroc-ice-python_6.0.0_all/DEBIAN/postrm': Permission denied
dpkg-deb: building package 'jderobot-zeroc-ice-python' in '.dpkg_pkgs/jderobot-zeroc-ice-python_6.0.0_all.deb'.
jderobot
dpkg-deb: building package 'jderobot' in '.dpkg_pkgs/jderobot_6.0.0_all.deb'.
-- Configuring incomplete, errors occurred!
See also "/home/leo/JdeRobot/base/build/CMakeFiles/CMakeOutput.log".
See also "/home/leo/JdeRobot/base/build/CMakeFiles/CMakeError.log".

**The following is the output of CMakeError.log**

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_543a6/fast && /usr/bin/make -f CMakeFiles/cmTC_543a6.dir/build.make CMakeFiles/cmTC_543a6.dir/build
make[1]: Entering directory '/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_543a6.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_543a6.dir/src.c.o   -c /home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_543a6
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_543a6.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_543a6.dir/src.c.o  -o cmTC_543a6 
CMakeFiles/cmTC_543a6.dir/src.c.o: In function `main':
**src.c:(.text+0x3e): undefined reference to `pthread_create'
src.c:(.text+0x4a): undefined reference to `pthread_detach'
src.c:(.text+0x5b): undefined reference to `pthread_join'
src.c:(.text+0x6f): undefined reference to `pthread_atfork'**
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_543a6.dir/build.make:86: recipe for target 'cmTC_543a6' failed
make[1]: *** [cmTC_543a6] Error 1
make[1]: Leaving directory '/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_543a6/fast' failed
make: *** [cmTC_543a6/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_91c16/fast && /usr/bin/make -f CMakeFiles/cmTC_91c16.dir/build.make CMakeFiles/cmTC_91c16.dir/build
make[1]: Entering directory '/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_91c16.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_91c16.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_91c16
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_91c16.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_91c16.dir/CheckFunctionExists.c.o  -o cmTC_91c16  -lpthreads 
**/usr/bin/ld: cannot find -lpthreads**
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_91c16.dir/build.make:86: recipe for target 'cmTC_91c16' failed
make[1]: *** [cmTC_91c16] Error 1
make[1]: Leaving directory '/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_91c16/fast' failed
make: *** [cmTC_91c16/fast] Error 2

Determining if the __i386__ exist failed with the following output:
Change Dir: /home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_8d344/fast && /usr/bin/make -f CMakeFiles/cmTC_8d344.dir/build.make CMakeFiles/cmTC_8d344.dir/build
make[1]: Entering directory '/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_8d344.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -std=c++11 -Wall -lpthread    -o CMakeFiles/cmTC_8d344.dir/CheckSymbolExists.cxx.o -c /home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:7:19: **error: ‘__i386__’ was not declared in this scope**
   return ((int*)(&__i386__))[argc];
                   ^~~~~~~~
/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:7:19: note: suggested alternative: ‘__k8__’
   return ((int*)(&__i386__))[argc];
                   ^~~~~~~~
                   __k8__
CMakeFiles/cmTC_8d344.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_8d344.dir/CheckSymbolExists.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_8d344.dir/CheckSymbolExists.cxx.o] Error 1
make[1]: Leaving directory '/home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_8d344/fast' failed
make: *** [cmTC_8d344/fast] Error 2

File /home/leo/JdeRobot/base/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef __i386__
  return ((int*)(&__i386__))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by jmplaza** [comment]
Hi @rk080299 ,

take a look at [this thread](https://github.com/JdeRobot/base/issues/1391#issuecomment-597009461)

"Watch out that ONLY Ubuntu-18.04, ROS Melodic and Gazebo-9 are supported right now. It is strongly recommended to install JdeRobot/base from debian package following [this recipe](https://jderobot.github.io/RoboticsAcademy/installation/#jderobot-base)."
