### ISSUE TITLE
JdeRobot Replayer Component

### ISSUE THREAD

**Issue by militaru92** [JdeRobot/base#175]
I have modified the replayer component so that it can replay data stored in a rosbag file. I also added my IceRosGazebo and my RosIceGazebo packages. However some problems have risen, after I added my code:
1. I noticed that during the compilation, the process percentile stays at 20% until the end.
2. When I type: "sudo make install" I get this error, although a simple "make" compiles everything:

Traceback (most recent call last):
  File "/opt/ros/jade/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py", line 41, in <module>
    from genmsg import EXT_MSG, EXT_SRV, MsgContext
ImportError: No module named genmsg

If someone can give me a hint of how can I fix this, please tell me.
The version of my code is at: https://github.com/militaru92/JdeRobot.git

**Comment by varhub** [comment]
I suppose that it isn't a simple solution. By the way, if it is, you must simply source your ROS environment prior to compile.

If it works, then next issue will be add a pre-build exec command into CMake to source it and rollback to avoid issues with next components.

**Background**
genmsg is a ROS package that post-create Stub and Skeleton classes for communication. This dependency should appear in your CMakeLists (ROS). For example, for *geometry_msgs*:
```
## Find catkin macros and libraries
## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
## is used, also find other catkin packages
find_package(catkin REQUIRED COMPONENTS
  genmsg
  std_msgs
)
...
## Generate messages in the 'msg' folder
add_message_files(
  FILES
  Point.msg
  Vector3.msg
  Quaternion.msg
  Pose.msg
)
...
## Generate added messages and services with any dependencies listed here
generate_messages(
  DEPENDENCIES
  std_msgs
)
```

To reproduce this issue, rename genmsg package under your ROS tree and try to compile (as always). If not, I'm mistaken. If you are lucky, you only need to edit `/opt/ros/hydro/share/genmsg/package.xml`
