### ISSUE TITLE
Discussion: Use single Ice Adapter

### ISSUE THREAD

**Issue by varhub** [JdeRobot/base#199]
Following recommendation from:
https://doc.zeroc.com/display/Ice35/Using+Multiple+Object+Adapters

_I suppose that share Ice adapter has been and introduced feature, but it seems to be available at least since ice3.4._

Advantages:
- Less code:
  - Single createObjectAdapterWithEndpoints at code
  - Single xxx.Endpoints entry at Ice.Config
- Single used port

This means that connect to several robots will be easy

I let here an example with two adapters:
https://github.com/varhub/JdeRobot/commit/b3f430d21048b04c208038269111bf241456690f

**Comment by fqez** [comment]
This would be interesting to talk about already, as well as #224 and #225. Nowadays is a pain to configure each execution of every example...

**Comment by fqez** [comment]
I refactored the turtlebot plugin to allow this feature, now:

* quadrotor2
* flyingkinect2 
* turtlebot

 have only one Ice adapter.
