### ISSUE TITLE
big problem with quadrotor and altitude feedback

### ISSUE THREAD

**Issue by varhub** [JdeRobot/base#273]
I implemented sonar based altitude for quadrotor (gazebo plugin). Tweaking "fly modes" I discovered a very ugly behavior.
1. altitude feedback is realized by a sonar sensor with a 3m of range
2. takeoff has been improved to allow altitude based milestone instead "go up for X seconds"
3. takeoff to fly threshold is editable by user (sdf)

=> If (3) is greater than (1), then (2) is never archived and quadrotor raise up forever.

**Solutions**
a. there is no option to merge data with gazebo's absolute position
b. only chance to overcome it is tweaking sonar sensor (sdf)
c. there is a 3rd way that implies a "barometer" like another ray sensor. Therefore it is almost (b) solution.

**Error is here but current sdf's parameters do not trigger it**
What is the best approach to overcome it?

**Comment by fqez** [comment]
Maybe I can take care of this if you want to.
