### ISSUE TITLE
Add backward compatibility in Image interface using addition

### ISSUE THREAD

**Issue by ojgarciab** [JdeRobot/base#53]
As commented in developer list, I'll implement backward compatibility using addition:
http://gsyc.escet.urjc.es/pipermail/jde-developers/2015-April/003755.html

Right now there is some components broken because this issue:
- kinect2server
- gazeboserver
- naoserver

I'll rename `getImageData(string format)` to `getImageDataWithFormat(string format)`.

The roadmap will be:
- [ ] Refactor `getImageData(string format)` to `getImageDataWithFormat(string format)`:
  - [ ] cameraserver
  - [ ] cameraview
  - [ ] recorder
  - [ ] replayer
  - [ ] naoviewer
  - [ ] teleoperator
  - [ ] followBall
  - [ ] colorTuner
  - [ ] basic_component_qt
  - [ ] openniServer
  - [ ] others (I'll check them all)
- [ ] Enabling backward compatibility to reference client and server:
  - [ ] cameraserver
  - [ ] cameraview
  - [ ] parallelIce

When the issue is assigned I'll start working with it.

PS: Please, write a coment If another name (instead `getImageDataWithFormat`) is suggested.

**Comment by varhub** [comment]
I'm totally agree with this, specially this part:
`Another change could be rename "getImageFormat" to "getImageFormats"`

PS: thanks to point out Ice's method overriding limitation

Another option to overcome this limitation is providing a implementation with basic logic.
I already did it, you can see it at https://github.com/jderobot-varribas/gazeboplugin-quadrotor2. Refer to **camerabasei** and **pushcamerai**.
