### ISSUE TITLE
New cars for gazebo

### ISSUE THREAD

**Issue by fqez** [JdeRobot/base#831]
The current vehicles of JdeRobot are a little messy and "unreal". We need to include new and more realistic looking cars in order to make the simulations more attractive.
It would be good to include kind of holonomic and non holonomic cars, meaning:

* "Holonomic" cars can rotate on its own axis like it has 360º wheel.
* "Non holonomic" cars behave like a real world car (ackermann geometry).

**Comment by fqez** [comment]
For the holonomic cars, I've adopted an sketchup model of a Audi RSQ (from the movie i,Robot) like shown in the image below. I've selected this car because it has no real wheels (the car levitates), so it makes more credible the fact that it can turn around its own axis.
I've made a normal and a taxi version of the car applying some colors and stuff.

* [x] Holonomic taxi
* [x] Holonomic car
* [ ] Non holonomic taxi
* [ ] Non holonomic car

**Taxi version:**
![imagen](https://user-images.githubusercontent.com/8070644/27264020-2a03d210-5476-11e7-959e-26fe6d667b19.png)

**Normal version:**
![imagen](https://user-images.githubusercontent.com/8070644/27264030-554ea31e-5476-11e7-8542-f2175b0579a2.png)

This is how it looks in Gazebo:

**Both taxi and normal versions:**
![imagen](https://user-images.githubusercontent.com/8070644/27264061-eee2cbf4-5476-11e7-8e4f-6a621574bcc5.png)

For the "non holonomic" car, I could choose whichever car I want or like, so I made my mind for the Mercedes SLS AMG. Again, this model has its normal and taxi version.

**Taxi version:**
![imagen](https://user-images.githubusercontent.com/8070644/27264071-1d49d35c-5477-11e7-8f46-a73e75477ffe.png)

**Normal version:**
![imagen](https://user-images.githubusercontent.com/8070644/27264090-8501f1aa-5477-11e7-91c2-eb25bf7afdbc.png)

**Comment by jmplaza** [comment]
Awesome Fran, fantastic cars! :-)

**Comment by fqez** [comment]
Now both holonomic cars have their own plugin (just as temporary solution). It would be good to refactor also the JdeRobot's gazebo plugins because there is so much code duplicated.
